gps_node:
  ros__parameters:
    port: /dev/ttyGPS # ajusta según tu sistema
    baudrate: 9600 # NEO-8M default, puedes subir a 38400 con u-center
    frame_id: gps_link
    read_hz: 10.0 # NEO-8M por defecto envía a 1Hz, sube con u-center a 10Hz
