camera_node:
  ros__parameters:
    device: /dev/video0         # verifica con: ls /dev/video*
    width: 1920
    height: 1080
    fps: 15
    frame_id: camera_link
    compressed_quality: 80      # calidad JPEG 0-100 para stream de debug remoto